name: Lint & Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . ".[dev]"
    - name: Test with pytest
      run: |
        # endpoints should be tested locally otherwise this would take too long
        pytest --ignore=tests/endpoints/
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . ".[dev]"
    - name: Setup Python 3.6
      uses: actions/setup-python@v2
    - name: Lint with black
      uses: psf/black@master
    - name: Lint with flake8
      run: flake8
